### ISSUE TITLE
Typing issues when importing library

### ISSUE THREAD

**Issue by Eliacus** [BirkhoffG/jax-dataloader#31]
Hey! I was trying out this package on a new, minimal python environment and got some typing related error when importing the package.

Environment:
- Python 3.11.8
packages:
```
beartype==0.18.0
jax==0.4.25
jax-dataloader==0.1.0
jaxlib==0.4.25
markdown-it-py==3.0.0
mdurl==0.1.2
ml-dtypes==0.4.0
numpy==1.26.4
opt-einsum==3.3.0
plum-dispatch==2.3.3
Pygments==2.17.2
rich==13.7.1
scipy==1.13.
```

Steps to reproduce:
```
import jax_dataloader
```

Stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/jax_dataloader/__init__.py", line 4, in <module>
    from .core import *
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/jax_dataloader/core.py", line 8, in <module>
    from .loaders import *
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/jax_dataloader/loaders/__init__.py", line 2, in <module>
    from .jax import *
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/jax_dataloader/loaders/jax.py", line 88, in <module>
    class DataLoaderJAX(BaseDataLoader):
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/jax_dataloader/loaders/jax.py", line 90, in DataLoaderJAX
    @typecheck
     ^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 87, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 136, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 174, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 239, in beartype_func
    func_wrapper_code = generate_code(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/wrap/wrapmain.py", line 118, in generate_code
    code_check_params = _code_check_args(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/wrap/_wrapargs.py", line 309, in code_check_args
    reraise_exception_placeholder(
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_util/error/utilerrraise.py", line 138, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_decor/wrap/_wrapargs.py", line 262, in code_check_args
    ) = make_code_raiser_func_pith_check(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 250, in _callable_cached
    raise exception
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 242, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
                                                          ^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_check/checkmake.py", line 311, in make_code_raiser_func_pith_check
    ) = make_check_expr(hint, conf, cls_stack)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 250, in _callable_cached
    raise exception
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 242, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
                                                          ^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_check/code/codemake.py", line 1752, in make_check_expr
    hint_child_placeholder=_enqueue_hint_child(
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/.virtualenvs/jax/lib/python3.11/site-packages/beartype/_check/code/codemake.py", line 526, in _enqueue_hint_child
    pith_child_expr is pith_curr_assign_expr
AssertionError: Method jax_dataloader.loaders.jax.DataLoaderJAX.__init__() parameter "dataset" type hint typing.Annotated[NoneType, Is[lambda _: hf_datasets is not None]] child pith expression '__beartype_pith_0' duplicates current pith assignment expression '__beartype_pith_0'.
```

**Comment by BirkhoffG** [comment]
It seems to be a bug in beartype. Can you update to the latest version `beartype==0.18.2` and see if this problem persists?

**Comment by Eliacus** [comment]
That solves it indeed! Not sure why pip installed `beartype==0.18.0` yesterday. Today it seems to install the package with `0.18.2` which works great

Thank you!
